"""Add relation between groups and posts

Revision ID: 1466a607b19e
Revises: 5529b827d54e
Create Date: 2024-09-09 20:57:31.017041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1466a607b19e'
down_revision = '5529b827d54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('event', 'group')
    op.drop_column('post', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('group')
    # ### end Alembic commands ###
