"""Add application link to post and events model

Revision ID: 54c4000ce6ff
Revises: f9dd827d5a2e
Create Date: 2024-09-11 09:00:07.828925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '54c4000ce6ff'
down_revision = 'f9dd827d5a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('application_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('post', sa.Column('application_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'application_link')
    op.drop_column('event', 'application_link')
    # ### end Alembic commands ###
