"""Change cascade delete location

Revision ID: 5529b827d54e
Revises: 820bb927c35e
Create Date: 2024-09-09 15:31:55.831443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5529b827d54e'
down_revision = '820bb927c35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
