"""Add Lecture model, add group column to Post model, add relation between lectures and posts

Revision ID: 820bb927c35e
Revises: dbd7100055ca
Create Date: 2024-09-06 23:07:13.744555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '820bb927c35e'
down_revision = 'dbd7100055ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lecture', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lecture', type_='foreignkey')
    op.drop_column('lecture', 'post_id')
    # ### end Alembic commands ###
