"""Change permissions

Revision ID: 93ad18956532
Revises: 54c4000ce6ff
Create Date: 2024-09-12 02:10:59.316284

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93ad18956532'
down_revision = '54c4000ce6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_updated_by_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('lecture', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('lecture_updated_by_fkey', 'lecture', type_='foreignkey')
    op.drop_constraint('lecture_post_id_fkey', 'lecture', type_='foreignkey')
    op.create_foreign_key(None, 'lecture', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lecture', 'user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('post', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint('post_updated_by_fkey', 'post', type_='foreignkey')
    op.drop_constraint('post_group_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'post', 'group', ['group_id'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('linked_in_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'is_public')
    op.drop_column('user', 'linked_in_url')
    op.drop_column('user', 'github_url')
    op.drop_column('user', 'department')
    op.drop_column('user', 'role')
    op.drop_column('user', 'photo_url')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_group_id_fkey', 'post', 'group', ['group_id'], ['id'])
    op.create_foreign_key('post_updated_by_fkey', 'post', 'user', ['updated_by'], ['id'])
    op.alter_column('post', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'lecture', type_='foreignkey')
    op.drop_constraint(None, 'lecture', type_='foreignkey')
    op.create_foreign_key('lecture_post_id_fkey', 'lecture', 'post', ['post_id'], ['id'])
    op.create_foreign_key('lecture_updated_by_fkey', 'lecture', 'user', ['updated_by'], ['id'])
    op.alter_column('lecture', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_updated_by_fkey', 'event', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###
