"""Change permissions

Revision ID: 9f547fece84b
Revises: 93ad18956532
Create Date: 2024-09-12 02:13:12.656852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9f547fece84b'
down_revision = '93ad18956532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
