"""Remove location field from post

Revision ID: b6429638c8e3
Revises: d311f47fcd4b
Create Date: 2024-09-05 18:57:22.814218

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b6429638c8e3'
down_revision = 'd311f47fcd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('post', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('event', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
