"""Change post and event relation to inheritance instead of composition

Revision ID: d311f47fcd4b
Revises: 1edadb6ee65a
Create Date: 2024-09-05 15:59:33.260336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd311f47fcd4b'
down_revision = '1edadb6ee65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'is_visible')
    op.drop_column('event', 'location')
    op.drop_column('event', 'image')
    op.drop_column('event', 'content')
    op.drop_column('event', 'description')
    op.drop_column('event', 'title')
    # ### end Alembic commands ###
