"""Add Lecture model, add group column to Post model, add relation between lectures and posts

Revision ID: dbd7100055ca
Revises: e60748bff2c4
Create Date: 2024-09-06 23:04:22.130792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dbd7100055ca'
down_revision = 'e60748bff2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('lecture', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('lecture', sa.Column('is_visible', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('group', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'group')
    op.drop_column('lecture', 'is_visible')
    op.drop_column('lecture', 'title')
    op.drop_column('event', 'group')
    # ### end Alembic commands ###
