name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker buildx prune -f
      - run: cp /home/hasan/ituacm_website_backend/.env ./
      - run: docker compose -f docker-compose.yml build --no-cache
      - run: docker compose -f docker-compose.yml up -d